// <auto-generated />
namespace ScanIT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedselectedquantityinorderdetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedselectedquantityinorderdetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202101202059100_added selected quantity in orderdetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
