// <auto-generated />
namespace ScanIT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedproductmodelandcontroller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedproductmodelandcontroller));
        
        string IMigrationMetadata.Id
        {
            get { return "202101142220582_added product model and controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
